# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift

before_install:
  - brew outdated xctool || brew upgrade xctool
  - carthage update

script:
  - set -o pipefail && xcodebuild -project "Sheeeeeeeeet.xcodeproj" -scheme "Sheeeeeeeeet" -sdk "iphonesimulator" | xcpretty -c
  - pod lib lint
  - fastlane test
